# DoS Master Framework - Target Templates
# Predefined target configurations for different scenarios

target_profiles:
  
  # Web server targets
  web_server_basic:
    description: "Basic web server (Apache/Nginx)"
    ports: [80, 443]
    recommended_attacks:
      - http_flood
      - slowloris
      - syn_flood
    considerations:
      - "Check for reverse proxy"
      - "Monitor connection limits"
      - "Test SSL/TLS handling"
    
  web_server_advanced:
    description: "Advanced web server with CDN"
    ports: [80, 443, 8080, 8443]
    recommended_attacks:
      - http_flood
      - slowloris
    considerations:
      - "May have DDoS protection"
      - "CDN might cache responses"
      - "Use realistic user agents"
  
  # Database servers
  mysql_server:
    description: "MySQL database server"
    ports: [3306]
    recommended_attacks:
      - syn_flood
      - connection_exhaustion
    considerations:
      - "Monitor connection pool"
      - "Check max_connections setting"
      - "Test query timeouts"
  
  postgresql_server:
    description: "PostgreSQL database server"
    ports: [5432]
    recommended_attacks:
      - syn_flood
      - connection_exhaustion
    considerations:
      - "Monitor active connections"
      - "Check connection limits"
      - "Test connection pooling"
  
  # Network infrastructure
  dns_server:
    description: "DNS server"
    ports: [53]
    recommended_attacks:
      - udp_flood
      - dns_amplification
    considerations:
      - "Test recursive queries"
      - "Monitor cache behavior"
      - "Check rate limiting"
  
  mail_server:
    description: "Mail server (SMTP/POP3/IMAP)"
    ports: [25, 110, 143, 993, 995]
    recommended_attacks:
      - syn_flood
      - connection_exhaustion
    considerations:
      - "Test SMTP handling"
      - "Monitor queue sizes"
      - "Check greylisting"
  
  # IoT and embedded devices
  iot_device:
    description: "IoT device (camera, router, etc.)"
    ports: [80, 443, 23, 22]
    recommended_attacks:
      - basic_icmp_test
      - basic_syn_test
    considerations:
      - "Limited CPU/memory"
      - "Use gentle attacks"
      - "Monitor device stability"
      - "Check for default credentials"
  
  router_device:
    description: "Network router/gateway"
    ports: [80, 443, 22, 23, 161]
    recommended_attacks:
      - icmp_flood
      - syn_flood
      - snmp_amplification
    considerations:
      - "Critical infrastructure"
      - "Monitor network impact"
      - "Check SNMP community strings"
  
  # Application servers
  api_server:
    description: "REST API server"
    ports: [80, 443, 8080, 8443]
    recommended_attacks:
      - http_flood
      - api_abuse
    considerations:
      - "Test rate limiting"
      - "Check authentication"
      - "Monitor API quotas"
  
  game_server:
    description: "Online game server"
    ports: [80, 443, 7777, 25565]
    recommended_attacks:
      - udp_flood
      - syn_flood
    considerations:
      - "Real-time requirements"
      - "Player impact"
      - "Anti-cheat systems"

# Environment-specific configurations
environments:
  
  development:
    description: "Development environment"
    safety_level: "high"
    max_duration: 300
    max_threads: 10
    allowed_attacks:
      - basic_icmp_test
      - basic_syn_test
      - basic_http_test
    
  testing:
    description: "Testing environment"
    safety_level: "medium"
    max_duration: 600
    max_threads: 25
    allowed_attacks:
      - icmp_flood
      - udp_flood
      - syn_flood
      - http_flood
      - slowloris
    
  staging:
    description: "Staging environment"
    safety_level: "medium"
    max_duration: 900
    max_threads: 50
    allowed_attacks:
      - icmp_flood
      - udp_flood
      - syn_flood
      - http_flood
      - slowloris
      - multi_vector
    
  production:
    description: "Production environment (AUTHORIZED ONLY)"
    safety_level: "low"
    max_duration: 1800
    max_threads: 100
    allowed_attacks:
      - comprehensive_dos
      - multi_vector
      - amplification
    warnings:
      - "PRODUCTION ENVIRONMENT"
      - "ENSURE PROPER AUTHORIZATION"
      - "HAVE ROLLBACK PLAN READY"
      - "NOTIFY STAKEHOLDERS"

# Testing scenarios
scenarios:
  
  penetration_test:
    description: "Standard penetration test"
    phases:
      - name: "reconnaissance"
        duration: 60
        attacks: ["port_scan", "service_enum"]
      - name: "light_testing"
        duration: 120
        attacks: ["basic_icmp_test", "basic_syn_test"]
      - name: "stress_testing"
        duration: 300
        attacks: ["network_stress_test", "web_server_stress"]
    
  red_team_exercise:
    description: "Red team exercise"
    phases:
      - name: "initial_probe"
        duration: 30
        attacks: ["basic_icmp_test"]
      - name: "escalation"
        duration: 180
        attacks: ["tcp_exhaustion_test"]
      - name: "full_assault"
        duration: 600
        attacks: ["comprehensive_dos"]
    
blue_team_training:
   description: "Blue team training"
   phases:
     - name: "detection_training"
       duration: 300
       attacks: ["basic_icmp_test", "basic_syn_test"]
       focus: "detection"
     - name: "mitigation_training"
       duration: 600
       attacks: ["network_stress_test"]
       focus: "mitigation"
     - name: "recovery_training"
       duration: 900
       attacks: ["comprehensive_dos"]
       focus: "recovery"
   
 compliance_testing:
   description: "Compliance and audit testing"
   phases:
     - name: "baseline_establishment"
       duration: 120
       attacks: ["basic_icmp_test"]
     - name: "vulnerability_validation"
       duration: 300
       attacks: ["syn_flood", "http_flood"]
     - name: "resilience_testing"
       duration: 600
       attacks: ["multi_vector"]
   
 capacity_testing:
   description: "Capacity and performance testing"
   phases:
     - name: "normal_load"
       duration: 180
       attacks: ["basic_http_test"]
     - name: "peak_load"
       duration: 300
       attacks: ["http_flood"]
     - name: "breaking_point"
       duration: 600
       attacks: ["comprehensive_dos"]

# Attack intensity levels
intensity_levels:
 
 minimal:
   description: "Minimal impact for basic testing"
   max_rate: 50
   max_threads: 3
   max_duration: 60
   suitable_for: ["development", "initial_testing"]
   
 light:
   description: "Light testing for vulnerability assessment"
   max_rate: 200
   max_threads: 8
   max_duration: 180
   suitable_for: ["testing", "vulnerability_scans"]
   
 moderate:
   description: "Moderate testing for realistic assessment"
   max_rate: 1000
   max_threads: 15
   max_duration: 300
   suitable_for: ["staging", "penetration_testing"]
   
 heavy:
   description: "Heavy testing for stress assessment"
   max_rate: 5000
   max_threads: 30
   max_duration: 600
   suitable_for: ["stress_testing", "capacity_planning"]
   
 extreme:
   description: "Extreme testing for breaking point analysis"
   max_rate: 20000
   max_threads: 100
   max_duration: 1800
   suitable_for: ["production_authorized", "red_team"]
   warnings:
     - "HIGH IMPACT TESTING"
     - "ENSURE PROPER AUTHORIZATION"
     - "HAVE MITIGATION READY"

# Common port configurations
common_ports:
 
 web_services:
   tcp: [80, 443, 8080, 8443, 8000, 8888]
   udp: []
   description: "Standard web service ports"
   
 database_services:
   tcp: [3306, 5432, 1433, 1521, 6379, 27017]
   udp: []
   description: "Common database ports"
   
 mail_services:
   tcp: [25, 110, 143, 993, 995, 587]
   udp: []
   description: "Email service ports"
   
 network_services:
   tcp: [22, 23, 53, 88, 135, 139, 445]
   udp: [53, 67, 68, 123, 161, 162, 514]
   description: "Network infrastructure ports"
   
 remote_access:
   tcp: [22, 23, 3389, 5900, 5901]
   udp: []
   description: "Remote access service ports"
   
 file_services:
   tcp: [21, 22, 139, 445, 2049]
   udp: [2049]
   description: "File sharing service ports"

# Recommended configurations by target type
recommendations:
 
 web_application:
   initial_assessment:
     attacks: ["basic_http_test", "basic_syn_test"]
     duration: 120
     intensity: "light"
   
   thorough_testing:
     attacks: ["http_flood", "slowloris", "syn_flood"]
     duration: 600
     intensity: "moderate"
   
   stress_testing:
     attacks: ["multi_vector"]
     duration: 1200
     intensity: "heavy"
 
 database_server:
   initial_assessment:
     attacks: ["basic_syn_test", "connection_test"]
     duration: 180
     intensity: "light"
   
   connection_testing:
     attacks: ["syn_flood", "connection_exhaustion"]
     duration: 300
     intensity: "moderate"
   
   resilience_testing:
     attacks: ["comprehensive_dos"]
     duration: 900
     intensity: "heavy"
 
 network_infrastructure:
   initial_assessment:
     attacks: ["basic_icmp_test", "basic_udp_test"]
     duration: 120
     intensity: "minimal"
   
   bandwidth_testing:
     attacks: ["icmp_flood", "udp_flood"]
     duration: 300
     intensity: "moderate"
   
   capacity_testing:
     attacks: ["multi_vector"]
     duration: 600
     intensity: "heavy"